# Generated by Django 5.2.17 on 2026-09-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_topichistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicesession',
            name='answer',
            field=models.TextField(blank=True),
        ),
    ]
