# Generated by Django 5.2.17 on 2026-09-18 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_practicesession_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeechAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True)),
                ('clarity_score', models.PositiveIntegerField(blank=True, null=True)),
                ('structure_score', models.PositiveIntegerField(blank=True, null=True)),
                ('vocabulary_score', models.PositiveIntegerField(blank=True, null=True)),
                ('fluency_score', models.PositiveIntegerField(blank=True, null=True)),
                ('filler_word_count', models.PositiveIntegerField(default=0)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='speech_analysis', to='practice.practicesession')),
            ],
        ),
    ]
